### ISSUE TITLE
Airtel tv!!! Please add irtel tv add on... As soon as possible  a kind request from all of us!!! 

### ISSUE THREAD

**Issue by Suraj824** [botallen/repository.botallen#50] opened 2020-06-01 10:49 UTC
## Feature request
For Add-on ... [e.g. Jiotv]
I'm submitting a proposal to ...
  - [x] new feature
  - [ ] change an existing feature

#### Development tips
Not obligatory, you can describe how you would develop it, attach links to already prepared code, etc...

**Comment by botallen** [comment] 2020-06-01 10:52
Duplicate of #40

**Closed by botallen** 2020-06-01 10:52 UTC
Labels: duplicate
