### ISSUE TITLE
Star channel not working

### ISSUE THREAD

**Issue by jack009j** [botallen/repository.botallen#259] opened 2022-01-25 08:34 UTC
star channel are not working, I logged with hotstar premium account and played some movie it played fine, but while playing channel(star vijay),it show connect to jio network,
Is necessary to have jiofiber connection to play star channel or jiosim enough?
Or it will play in any network?
![Screenshot_2022-01-25-13-32-26-93](https://user-images.githubusercontent.com/79247377/150940792-8f7ba5e5-8e52-462a-b9d2-e00d6a12d5c6.jpg)

Add-on name: Jiotv&hotstar
Add-on version: 2.2.2&1.1.1
Kodi version: Kodi 19.3
Operating system version/name: Android 9
Using from country: India

**Comment by iMro0t** [comment] 2022-01-25 08:39
Duplicate of #172

**Closed by iMro0t** 2022-01-25 08:39 UTC
Labels: bug
