### ISSUE TITLE
Jio plays only in 480 resolutions 

### ISSUE THREAD

**Issue by setushah1** [botallen/repository.botallen#179] opened 2021-08-15 02:12 UTC
## Feature request
For Add-on Jiotv
I'm submitting a proposal to increase the resolution to best possible one. Currently all the channels are only in 480P

#### Is your feature request related to a problem? 
No

**Comment by iMro0t** [comment] 2021-09-03 15:10
Duplicate of #132

**Closed by iMro0t** 2021-09-03 15:10 UTC
Labels: enhancement
