### ISSUE TITLE
HD Channels are not HD?

### ISSUE THREAD

**Issue by SSoft7** [botallen/repository.botallen#164] opened 2021-08-02 14:58 UTC
**Your Environment**
- Add-on name: JioTV
- Add-on version: Latest 2.2.1
- Kodi version: 19.1 Stable Matrix
- Operating system version/name: Windows 10

**Describe the bug**
I am not sure if this is a bug but Most Hindi HD Channels are playing at non-HD resolutions. For example - 
Zee TV HD - 576x432
Sony HD - 854x480
Sony Max HD - Same

**To Reproduce**
When Playing any Channel Click Settings -> Video Settings.

**Expected behavior**
Expecting HD resolution for HD channels.

**Debug log**
I suppose this is a known issue, so not attaching logs right now, but if needed let me know.

**Comment by iMro0t** [comment] 2021-08-02 15:09
Duplicate of #132

**Closed by iMro0t** 2021-08-02 15:09 UTC
Labels: bug
