### ISSUE TITLE
Bro many people are asking addon. Who will release the addon. It's admin you or any other people

### ISSUE THREAD

**Issue by Tigerroshan** [botallen/repository.botallen#208] opened 2021-09-16 09:00 UTC
Who will release the addon for requested???
Please respond admin.
Any contact to creaters of addon.  Or only the admin @iMro0t  will release. Please reply......

**Comment by iMro0t** [comment] 2021-09-16 09:07
Duplicate of #206

**Closed by iMro0t** 2021-09-16 09:07 UTC
Labels: enhancement
