### ISSUE TITLE
Jio TV not working today 

### ISSUE THREAD

**Issue by pankajsingasane** [botallen/repository.botallen#240] opened 2021-12-14 04:56 UTC
**Your Environment**
- Add-on name: [e.g. Jiotv]
- Add-on version: [e.g. 2.0.0]
- Kodi version: [e.g. Kodi 19]
- Operating system version/name: [e.g. Windows 10, LibreElec 9.0, etc...]
- Using from country: [eg. India, USA, etc...]

**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Additional context**

**Debug log**

The debug log can be found from this link:

Jio tv not working today
![16394577803076280964258838860728](https://user-images.githubusercontent.com/9843139/145935667-e6d2c816-2295-407b-bb93-bbfa10f5f874.jpg)

**Comment by iMro0t** [comment] 2021-12-14 05:33
Duplicate of #236

**Closed by iMro0t** 2021-12-14 05:33 UTC
Labels: bug
