### ISSUE TITLE
Not working in my Android mobile kodi v18.6

### ISSUE THREAD

**Issue by trekvr** [botallen/repository.botallen#38] opened 2020-05-17 16:59 UTC
Hi,

 Thanks for the repository. But it is not working in v 18.6 kodi (android).Please let me know if there is any work around or working kodi version.

**Comment by bhargav1822** [comment] 2020-05-17 17:04
I cant login into new update 😭😭😭

What happened??

**Comment by botallen** [comment] 2020-05-17 17:16
> Hi,
> 
>  Thanks for the repository. But it is not working in v 18.6 kodi (android).Please let me know if there is any work around or working kodi version.

Please be more specific. In which add-on you are facing problem.

**Comment by trekvr** [comment] 2020-05-17 19:08
Hi,

Jiotv is not working in kodi v18.6 ( Android 9 mobile )

**Comment by botallen** [comment] 2020-05-18 05:55
@trekvr  Are you getting any Error message in notification ? Also make sure you are entering valid credentials. Also log can be helpful.

**Comment by vijaysolanki10** [comment] 2020-05-18 15:42
I tried on my mobile.
Getting error "bad request" while logging in.

**Comment by trekvr** [comment] 2020-05-18 16:03
> @trekvr Are you getting any Error message in notification ? Also make sure you are entering valid credentials. Also log can be helpful.

Hi,

 PFA log. 
[kodi.log](https://github.com/botallen/repository.botallen/files/4645252/kodi.log)

>

**Comment by botallen** [comment] 2020-05-19 15:35
@trekvr  I saw the log and looks like background service not started when you played channels. Did you seen any notification like `Jiotv background service stareted` . If you are still facing issue then come to the discord i'll resolve your issue. Currently i can't reproduce this and it's working in android so closing this issue. [discord](botallen.com/discord)

**Closed by botallen** 2020-05-19 15:35 UTC
