### ISSUE TITLE
Disney Hotstar not working with VPN on Kodi with Raspberry PI4

### ISSUE THREAD

**Issue by sandeshindi** [botallen/repository.botallen#77] opened 2020-08-21 22:57 UTC
It gives an error "Your VPN provider does not support Hotstar". But it works fine on kodi if I try it in macOS

**Comment by botallen** [comment] 2020-09-22 05:42
VPN is not supported in Disney+ Hotstar

**Comment by weyzax** [comment] 2021-05-22 06:43
@sandeshindi Could you provide more information on the VPN and the OS distro you are using for the Kodi build on the RPi4? I had similar issues connecting to Disney+ and Hotstar using VPN on LibreELEC. The underlying issue was not that it didn't work with VPN but how DNS nameserver was resolved. The DNS leaks were the cause of geolocation blocks.

**Comment by weyzax** [comment] 2021-05-22 06:46
After connecting to the VPN, could you test for DNS Leaks using this [addon](https://github.com/Space2Walker/plugin.program.dnsleaktest) and update the results here?

**Comment by iMro0t** [comment] 2021-08-01 11:44
Closing this issue. VPN support is impossible

**Closed by iMro0t** 2021-08-01 11:44 UTC
Labels: Disney+ Hotstar, help wanted
