### ISSUE TITLE
Jiotv has stopped working from evening. 

### ISSUE THREAD

**Issue by Dksb123456** [botallen/repository.botallen#239] opened 2021-12-13 17:27 UTC

**Comment by Asies23** [comment] 2021-12-13 17:45
https://github.com/botallen/repository.botallen/issues/236#issuecomment-992687172

**Comment by ABHI1152** [comment] 2021-12-13 18:15
I have updated still channels are not working plz help

**Comment by rupmagic** [comment] 2021-12-13 18:56
Still not working

**Comment by mhunny** [comment] 2021-12-14 03:51
Yes its not working now since 13th December, 2021, evening, not able to stream channels after clicking, without showing any errors. If anyone found some solution, please let us know. thanks

**Comment by iMro0t** [comment] 2021-12-14 05:31
Update to v2.2.2 and relogin

**Comment by iMro0t** [comment] 2021-12-14 05:32
Duplicate of #236

**Closed by iMro0t** 2021-12-14 05:32 UTC
