### ISSUE TITLE
Kindly add option for full Hd in jio tv

### ISSUE THREAD

**Issue by Ravikirandw** [botallen/repository.botallen#170] opened 2021-08-05 08:56 UTC
Kindly add option for full Hd in jio tv it almost doesn't switch to full hd

**Comment by iMro0t** [comment] 2021-08-05 08:58
Duplicate of #132 

https://github.com/botallen/repository.botallen/issues/132#issuecomment-826751544

**Closed by iMro0t** 2021-08-05 08:58 UTC
Labels: enhancement
