### ISSUE TITLE
Channels are not working

### ISSUE THREAD

**Issue by ManikandanGuru** [botallen/repository.botallen#59] opened 2020-06-24 19:15 UTC
Except for Star channels, most of the channels I selected didn't work at all. Tried Tamil channels none of it worked. Channels other than Star Sports are not working. Reinstalled repo, updated add-ons. Nothing helped. Is there any way to fix this please?

**Comment by botallen** [comment] 2020-06-25 04:56
@ManikandanGuru  please follow issue template so i can understand in details about your issue. Add log file and try relogin.

**Comment by botallen** [comment] 2020-06-25 05:07
Duplicate of #56

**Closed by botallen** 2020-06-25 05:07 UTC
