### ISSUE TITLE
The dependancy on xbmc.python versio 2.250 could not be satisfied

### ISSUE THREAD

**Issue by vijaysolanki10** [botallen/repository.botallen#112] opened 2021-02-23 07:33 UTC
Android TV Box Running Android 7.1
Kodi Version 19.0

Earlier it was working flawlessly, recently it started giving issues like not able to play any channels and taking much time to load TV.
So, yesterday I removed the add-ons and updated to the Kodi 19.0. I added the repository as advised on your site, but I could not find the add-ons to install, though I was able to search add-ons.

I tested this with Kodi on Window 10 to see if anything was wrong with my Android TV Box, but it gave same error.

**Comment by iMro0t** [comment] 2021-02-23 07:41
Duplicate of #107

**Closed by iMro0t** 2021-02-23 07:41 UTC
Labels: bug

**Comment by pshewale-dev** [comment] 2021-02-23 14:25
Downgrade the Kodi version to 18.9
