### ISSUE TITLE
Star channels only work through Jio network (Mobile and fiber)

### ISSUE THREAD

**Issue by Reptosblitz** [botallen/repository.botallen#176] opened 2021-08-11 20:22 UTC
**Your Environment**
- Disney+Hotstar
- 1.1.0
- Kodi 19.1
- Windows 7, Android TV 9 and android 9
- India

**Describe the bug**
I have been using your addon for a while now and its works like a clockwork absolutely amazing. Earlier I was using Jio fiber connection and everything use to work fine on it even star channels through guide or directly though addon but now I changed my connection to airtel fiber and star channels stop working for me. I always receive error saying " Use jio network to play this content" whenever i try to access it with airtel fiber connection. With jio mobile net it starts working like it suppose to be.

**To Reproduce**
1. Go to TV section of kodi and start a star channel on jio network
2. It will work fine 
3. Now change the device network to airtel connection 
4. Start star channel in kodi it wont work and display error "Use jio network to play this content".

**Expected behavior**
I was hoping that star channels would work on all networks not just jio.

**Screenshots**
`<a href="https://ibb.co/qJ2RwC1"><img src="https://i.ibb.co/qJ2RwC1/Screenshot-20210811-181205.png" alt="Screenshot-20210811-181205" border="0"></a>`

**Additional context**
Your addon is amazing and thanks for your hard work. 

**Debug log**

The debug log can be found from this link: https://paste.kodi.tv/azepukibaj.kodi

**Comment by iMro0t** [comment] 2021-08-12 03:13
Duplicate of #172

**Closed by iMro0t** 2021-08-12 03:13 UTC
Labels: bug
