### ISSUE TITLE
JioTV plug-in still working

### ISSUE THREAD

**Issue by nepalicana** [botallen/repository.botallen#6] opened 2020-04-05 20:53 UTC
Hi there,
Really love your work, I had been using your JioTV plugin since couple of days and find it awesome. It is good to use for non jio fiber users but since couple of days there has been issue that non of the channels work for me. Does anyone has the same issues? I don’t get any errors though when I click the channels the “working...” thing come up then disappear but doesn’t load any channels. Hope I can get a fix.

**Comment by ram2141** [comment] 2020-04-06 04:29
Hello @botallen,
I would like to take the opportunity to thank you for the wonderful work you are doing for the community. I am having same problem @nepalicana. For some reason, it works fine for 5 sec and buffers a lot. I have 300Mbps internet and don't think it is internet issue. I am from the US, Do I need to use Indian VPN? Is it possible to use this script without an Indian VPN, it could be my slow VPN. Will appreciate it if you could look into the error and provide a fix. Thank you so much for your work.

**Comment by botallen** [comment] 2020-04-06 06:54
> Really love your work, I had been using your JioTV plugin since couple of days and find it awesome.

Thanks for that.


> since couple of days there has been issue that non of the channels work for me. Does anyone has the same issues? I don’t get any errors though when I click the channels the “working...” thing come up then disappear but doesn’t load any channels. Hope I can get a fix.

Make sure you are on latest version v1.0.8-4.
If you are still facing the issue then send me log and i'll help you to fix it.
Currently i can't reproduce your problem channels are working for me.

**Comment by botallen** [comment] 2020-04-06 06:57
> I would like to take the opportunity to thank you for the wonderful work you are doing for the community. 

Thanks for that.



> I am having the same problem @nepalicana. For some reason, it works fine for 5 sec and buffers a lot even tho I watch it in low quality. I have 300Mbps internet and don't think it is an internet issue. I am from the US, Do I need to use Indian VPN? Is it possible to use this script without an Indian VPN, it could be my slow VPN. Will appreciate it if you could look into the error and provide a fix. Thank you so much for your work.

Yes you have to use Indian VPN. Currently there is not other way to use it without Indian VPN. Provide me detailed log so i can check what is the problem. Also make sure that you have latest version v1.0.8-4

**Comment by nepalicana** [comment] 2020-04-06 07:25
Hey there
Here is a link to my log 

https://paste.kodi.tv/iralosuwip

Appreciated if you could give me some solutions. The Addon was working simply fine few days ago and now with the problem not loading any live stream.

**Comment by nepalicana** [comment] 2020-04-06 09:32
> > I would like to take the opportunity to thank you for the wonderful work you are doing for the community. 
> 
> 
> 
> Thanks for that.
> 
> 
> 
> 
> 
> 
> 
> > I am having the same problem @nepalicana. For some reason, it works fine for 5 sec and buffers a lot even tho I watch it in low quality. I have 300Mbps internet and don't think it is an internet issue. I am from the US, Do I need to use Indian VPN? Is it possible to use this script without an Indian VPN, it could be my slow VPN. Will appreciate it if you could look into the error and provide a fix. Thank you so much for your work.
> 
> 
> 
> Yes you have to use Indian VPN. Currently there is not other way to use it without Indian VPN. Provide me detailed log so i can check what is the problem. Also make sure that you have latest version v1.0.8-4
> 
> 
> 
> 

@Botallen yes I did an update for the addon and I’m on version 1.0.8-4

Here is the log file
https://pastebin.com/EyVDgpu8

Appreciated if you could give me some solutions. The Addon was working simply fine few days ago and now with the problem not loading any live stream.

**Comment by botallen** [comment] 2020-04-06 09:55
> > > I would like to take the opportunity to thank you for the wonderful work you are doing for the community.
> > 
> > 
> > Thanks for that.
> > > I am having the same problem @nepalicana. For some reason, it works fine for 5 sec and buffers a lot even tho I watch it in low quality. I have 300Mbps internet and don't think it is an internet issue. I am from the US, Do I need to use Indian VPN? Is it possible to use this script without an Indian VPN, it could be my slow VPN. Will appreciate it if you could look into the error and provide a fix. Thank you so much for your work.
> > 
> > 
> > Yes you have to use Indian VPN. Currently there is not other way to use it without Indian VPN. Provide me detailed log so i can check what is the problem. Also make sure that you have latest version v1.0.8-4
> 
> @botallen yes I did an update for the addon and I’m on version 1.0.8-4
> 
> Here is the log file
> https://pastebin.com/EyVDgpu8
> 
> Appreciated if you could give me some solutions. The Addon was working simply fine few days ago and now with the problem not loading any live stream.

Did you try with reinstall ? Because from log i can see one of the dependency inputstreamhelper is causing problem. 
Goto my addons and reinstall both inputstreamhelper and jiotv plugin.

**Comment by botallen** [comment] 2020-04-08 07:14
> > > > > I would like to take the opportunity to thank you for the wonderful work you are doing for the community.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Thanks for that.
> > 
> > 
> > > > > I am having the same problem @nepalicana. For some reason, it works fine for 5 sec and buffers a lot even tho I watch it in low quality. I have 300Mbps internet and don't think it is an internet issue. I am from the US, Do I need to use Indian VPN? Is it possible to use this script without an Indian VPN, it could be my slow VPN. Will appreciate it if you could look into the error and provide a fix. Thank you so much for your work.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Yes you have to use Indian VPN. Currently there is not other way to use it without Indian VPN. Provide me detailed log so i can check what is the problem. Also make sure that you have latest version v1.0.8-4
> > 
> > 
> > > 
> > 
> > 
> > > @botallen yes I did an update for the addon and I’m on version 1.0.8-4
> > 
> > 
> > > 
> > 
> > 
> > > Here is the log file
> > 
> > 
> > > https://pastebin.com/EyVDgpu8
> > 
> > 
> > > 
> > 
> > 
> > > Appreciated if you could give me some solutions. The Addon was working simply fine few days ago and now with the problem not loading any live stream.
> > 
> > 
> > Did you try with reinstall ? Because from log i can see one of the dependency inputstreamhelper is causing problem.
> > Goto my addons and reinstall both inputstreamhelper and jiotv plugin.
> 
> @botallen I reinstalled both JioTV and inputstreamhelper as you mentioned and I don’t get any errors but non of the channels work expect those of Star networks like Star gold/sports. Is it due to the server problem? Here is the log file after reinstall.
> 
> https://paste.kodi.tv/ucukeyareb

Seems like proxy is not working. Did you get `Proxy server started` notification on startup ?

**Comment by nepalicana** [comment] 2020-04-08 09:00
@botallen working like a charm now. The only thing VOD has not been working ever since I installed the addon. It shows in the sub menus of every channels but when I try to click and open, it just simply don’t respond. Anyway it doesn’t bother me unless the channel works bro. Thanks for the generous help to the community. I would like to make a tutorial video on your addon so that wide community knows about your addon. And will there be JioCinema addon sometime soon? :)

**Comment by botallen** [comment] 2020-04-08 10:02
JioCinema is under development. Currently it has lot's of bugs and don't have much time for this so will be available soon on this repo. If catchup is not working for all channels then please provide me the log so i can look further into that. :)

**Comment by nepalicana** [comment] 2020-04-09 00:54
> JioCinema is under development. Currently it has lot's of bugs and don't have much time for this so will be available soon on this repo. If catchup is not working for all channels then please provide me the log so i can look further into that. :)

Here is the log file for catchup not responding. It neither gives any errors nor it loads any video while I try out any of the catchups. 

https://paste.kodi.tv/acisewucox

**Comment by botallen** [comment] 2020-04-17 11:31
@nepalicana  closing this issue. Reopen it if you are still facing issue.

**Closed by botallen** 2020-04-17 11:31 UTC
