### ISSUE TITLE
Jio service has crashed 

### ISSUE THREAD

**Issue by vishith** [botallen/repository.botallen#94] opened 2020-10-30 10:39 UTC
**Your Environment**
- Jiotv
- 2.0.13
- Mac OSX catalina

The Jio tv add-on keeps crashing and it says restarts and doesn't open

**Comment by iMro0t** [comment] 2020-11-10 11:10
Duplicate of #92

**Closed by iMro0t** 2020-11-10 11:10 UTC
Labels: bug

**Comment by parthdevloper** [comment] 2020-11-10 17:17
+1
