### ISSUE TITLE
Add Airtel Tv support

### ISSUE THREAD

**Issue by OMMJAI** [botallen/repository.botallen#157] opened 2021-07-22 07:56 UTC
## Feature request
For Add-on ... [e.g. Jiotv]
I'm submitting a proposal to ...
  - Add Airtel Tv support 
  - Also to add alll these channels as thumbnails in Kodi dashboard

#### Is your feature request related to a problem? Please describe.
Hi I really enjoy the Kodi add-on but would also like to add Airtel tv support fr better streaming quality of channels and more choice. Also I f you could have a thumbnail of suggested tv shows and movies on the Kodi dashboard

**Comment by iMro0t** [comment] 2021-07-31 17:33
Duplicate of #40

**Closed by iMro0t** 2021-07-31 17:33 UTC
