### ISSUE TITLE
streaming quality

### ISSUE THREAD

**Issue by vigneshboolog** [botallen/repository.botallen#151] opened 2021-07-14 17:43 UTC
hi, the streaming quality in jiotv in set to very low. Is there any way i can change the streaming quality to HD

**Comment by mkp95** [comment] 2021-07-22 12:23
I have the exact opposite problem. It's always more than enough for me. I would like to get a multi quality option if possible.

**Comment by spknair** [comment] 2021-07-25 16:37
> hi, the streaming quality in jiotv in set to very low. Is there any way i can change the streaming quality to HD

I am also getting stream at 480p only 😥

**Comment by iMro0t** [comment] 2021-07-31 17:36
Duplicate of #132

**Closed by iMro0t** 2021-07-31 17:36 UTC
