### ISSUE TITLE
Add support for channel guide.

### ISSUE THREAD

**Issue by ricky176** [botallen/repository.botallen#54] opened 2020-06-06 05:17 UTC
## Feature request
For Add-on ... [e.g. Jiotv]
I'm submitting a proposal to ...
  - [ ] new feature
  - [ ] change an existing feature

#### Development tips
Not obligatory, you can describe how you would develop it, attach links to already prepared code, etc...

**Comment by botallen** [comment] 2020-06-06 05:22
Duplicate of #55

**Closed by botallen** 2020-06-06 05:22 UTC
